In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns #data vis
from matplotlib import pyplot as plt #data vis

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv

In [2]:
td = pd.read_csv("/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")
td.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
td.Churn.value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [4]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
td.TotalCharges = pd.to_numeric(td.TotalCharges, errors = 'coerce')
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
td.TotalCharges.isnull().sum()

11

In [7]:
td['TotalCharges'] = td['TotalCharges'].replace(" ",np.nan)
td = td[td['TotalCharges'].notnull()]
td.TotalCharges.isnull().sum()

0

In [8]:
td['SeniorCitizen'] = td.SeniorCitizen.astype('object')

td.describe().round()

       tenure  MonthlyCharges  TotalCharges
count  7032.0          7032.0        7032.0
mean     32.0            65.0        2283.0
std      25.0            30.0        2267.0
min       1.0            18.0          19.0
25%       9.0            36.0         401.0
50%      29.0            70.0        1397.0
75%      55.0            90.0        3795.0
max      72.0           119.0        8685.0

In [10]:
df = td.copy()

In [12]:
df.drop(["customerID"], axis=1, inplace=True)

In [14]:
df['SeniorCitizen'].value_counts()

No     3639
Yes    3393
Name: Partner, dtype: int64

In [15]:
df['Partner'].value_counts()

No     3639
Yes    3393
Name: Partner, dtype: int64

In [16]:
df['Partner'] = df['Partner'].map(lambda s :1  if s =='Yes' else 0)
df['Partner'].value_counts()

0    3639
1    3393
Name: Partner, dtype: int64

In [17]:
df['Dependents'] = df['Dependents'].map(lambda s :1  if s =='Yes' else 0)
df['PhoneService'] = df['PhoneService'].map(lambda s :1  if s =='Yes' else 0)
df['PaperlessBilling'] = df['PaperlessBilling'].map(lambda s :1  if s =='Yes' else 0)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   object
 2   Partner           7032 non-null   int64
 3   Dependents        7032 non-null   int64
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   int64
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   int64
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(5), object(13)
memory usage: 1.1+ MB

In [22]:
df = pd.get_dummies(df, columns = ['gender','MultipleLines','InternetService',
'OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaymentMethod','Churn'], drop_first = True)

In [24]:

df['SeniorCitizen'] = df['SeniorCitizen'].map(lambda s :1  if s =='Yes' else 0)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   Partner                                7032 non-null   int64
 2   Dependents                             7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   PhoneService                           7032 non-null   int64
 5   PaperlessBilling                       7032 non-null   int64
 6   MonthlyCharges                         7032 non-null   float64
 7   TotalCharges                           7032 non-null   float64
 8   gender_Male                            7032 non-null   uint8
 9   MultipleLines_No phone service         7032 non-null   uint8
 10  MultipleLines_Yes                      7032 non-null   uint8
 11  InternetService_Fiber optic            7032 non-null   uint8
 12  InternetService_No                     7032 non-null   uint8
 13  OnlineSecurity_No internet service     7032 non-null   uint8
 14  OnlineSecurity_Yes                     7032 non-null   uint8
 15  OnlineBackup_No internet service       7032 non-null   uint8
 16  OnlineBackup_Yes                       7032 non-null   uint8
 17  DeviceProtection_No internet service   7032 non-null   uint8
 18  DeviceProtection_Yes                   7032 non-null   uint8
 19  TechSupport_No internet service        7032 non-null   uint8
 20  TechSupport_Yes                        7032 non-null   uint8
 21  StreamingTV_No internet service        7032 non-null   uint8
 22  StreamingTV_Yes                        7032 non-null   uint8
 23  StreamingMovies_No internet service    7032 non-null   uint8
 24  StreamingMovies_Yes                    7032 non-null   uint8
 25  Contract_One year                      7032 non-null   uint8
 26  Contract_Two year                      7032 non-null   uint8
 27  PaymentMethod_Credit card (automatic)  7032 non-null   uint8
 28  PaymentMethod_Electronic check         7032 non-null   uint8
 29  PaymentMethod_Mailed check             7032 non-null   uint8
 30  Churn_Yes                              7032 non-null   uint8
dtypes: float64(2), int64(6), uint8(23)
memory usage: 652.4 KB

In [27]:
df['TotalCharges'] = pd.to_numeric(df.TotalCharges, errors = 'coerce')
df.drop(['TotalCharges'], axis = 1, inplace = True)

In [28]:
df['Churn_Yes'] = df['Churn_Yes'].astype(int)
Y = df["Churn_Yes"].values
X = df.drop(labels = ["Churn_Yes"],axis = 1)
# Create Train & Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=101)

In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
result = model.fit(X_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [31]:
from sklearn import metrics
prediction_test = model.predict(X_test)# Print the prediction accuracy
print (metrics.accuracy_score(y_test, prediction_test))

0.8088130774697939

In [32]:
weights = pd.Series(model.coef_[0],
 index=X.columns.values)
weights.sort_values(ascending = False)

InternetService_Fiber optic              0.804254
PaperlessBilling                         0.321776
PaymentMethod_Electronic check           0.314968
MultipleLines_Yes                        0.263957
StreamingTV_Yes                          0.215431
StreamingMovies_Yes                      0.182079
MultipleLines_No phone service           0.114453
gender_Male                              0.042133
Partner                                  0.012802
MonthlyCharges                           0.005887
SeniorCitizen                            0.000000
DeviceProtection_Yes                    -0.020011
tenure                                  -0.034049
PaymentMethod_Mailed check              -0.078247
OnlineSecurity_No internet service      -0.091483
InternetService_No                      -0.091483
DeviceProtection_No internet service    -0.091483
TechSupport_No internet service         -0.091483
StreamingTV_No internet service         -0.091483
StreamingMovies_No internet service     -0.091483
OnlineBackup_No internet service        -0.091483
PaymentMethod_Credit card (automatic)   -0.117734
OnlineBackup_Yes                        -0.123135
Dependents                              -0.168283
TechSupport_Yes                         -0.391866
OnlineSecurity_Yes                      -0.430505
PhoneService                            -0.509307
Contract_One year                       -0.714961
Contract_Two year                       -1.354192
dtype: float64

All the customers that are likely to churn have positive values and customers unlikely to churn have negative values.